"""
exporter.py
Export module for MOMentum.
Exports a MOMDocument to .txt, .md, or .pdf formats.
"""

import os
from datetime import datetime
from pathlib import Path
from fpdf import FPDF
from formatter import MOMDocument

def _safe_filename(title: str, ext: str) -> str:
    """Generate a safe filename from meeting title and extension."""
    safe = title.replace(" ", "_").replace("/", "-").replace("\\", "-")
    safe = "".join(c for c in safe if c.isalnum() or c in "_-")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M")
    return f"MOM_{timestamp}_{safe}.{ext}"


def _ensure_output_dir(output_dir: str) -> str:
    """Create output directory if it doesn't exist."""
    os.makedirs(output_dir, exist_ok=True)
    return output_dir


def export_txt(mom: MOMDocument, output_dir: str = "output") -> str:

    _ensure_output_dir(output_dir)
    filename = _safe_filename(mom.title, "txt")
    filepath = os.path.join(output_dir, filename)

    def fmt_list(items, empty="None identified."):
        if not items:
            return f"  {empty}\n"
        return "\n".join(f"  [ ] {item}" for item in items) + "\n"

    def fmt_plain(items, empty="None identified."):
        if not items:
            return f"  {empty}\n"
        return "\n".join(f"  - {item}" for item in items) + "\n"

    sep = "=" * 44

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(f"{sep}\n")
        f.write(f"       MINUTES OF MEETING\n")
        f.write(f"{sep}\n")
        f.write(f"  Title        : {mom.title}\n")
        f.write(f"  Date         : {mom.date}\n")
        f.write(f"  Duration     : {mom.duration}\n")
        f.write(f"  Language     : {mom.language}\n")
        f.write(f"  Audio File   : {mom.audio_file}\n")
        f.write(f"  Generated At : {mom.generated_at}\n")
        f.write(f"{sep}\n\n")

        f.write(f"DISCUSSION SUMMARY\n")
        f.write(f"{'-'*44}\n")
        f.write(f"{mom.overview}\n\n")

        f.write(f"ACTION ITEMS\n")
        f.write(f"{'-'*44}\n")
        f.write(fmt_list(mom.action_items))
        f.write("\n")

        f.write(f"DECISIONS MADE\n")
        f.write(f"{'-'*44}\n")
        f.write(fmt_plain(mom.decisions))
        f.write("\n")

        f.write(f"NEXT STEPS\n")
        f.write(f"{'-'*44}\n")
        f.write(fmt_plain(mom.next_steps))
        f.write("\n")

        f.write(f"{sep}\n")
        f.write(f"Generated by MOMentum\n")
        f.write(f"https://github.com/HaitaanshDixit/MOMentum\n")
        f.write(f"{sep}\n")

    print(f"  Exported TXT : {filepath}")
    return filepath


def export_md(mom: MOMDocument, output_dir: str = "output") -> str:

    _ensure_output_dir(output_dir)
    filename = _safe_filename(mom.title, "md")
    filepath = os.path.join(output_dir, filename)

    def fmt_list(items, empty="None identified."):
        if not items:
            return f"_{empty}_\n"
        return "\n".join(f"- [ ] {item}" for item in items) + "\n"

    def fmt_plain(items, empty="None identified."):
        if not items:
            return f"_{empty}_\n"
        return "\n".join(f"- {item}" for item in items) + "\n"

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(f"# Minutes of Meeting\n\n")
        f.write(f"| Field | Value |\n")
        f.write(f"|---|---|\n")
        f.write(f"| **Title** | {mom.title} |\n")
        f.write(f"| **Date** | {mom.date} |\n")
        f.write(f"| **Duration** | {mom.duration} |\n")
        f.write(f"| **Language** | {mom.language} |\n")
        f.write(f"| **Audio File** | {mom.audio_file} |\n")
        f.write(f"| **Generated At** | {mom.generated_at} |\n\n")

        f.write(f"---\n\n")

        f.write(f"## Discussion Summary\n\n")
        f.write(f"{mom.overview}\n\n")

        f.write(f"---\n\n")

        f.write(f"## Action Items\n\n")
        f.write(fmt_list(mom.action_items))
        f.write("\n")

        f.write(f"## Decisions Made\n\n")
        f.write(fmt_plain(mom.decisions))
        f.write("\n")

        f.write(f"## Next Steps\n\n")
        f.write(fmt_plain(mom.next_steps))
        f.write("\n")

        f.write(f"---\n\n")
        f.write(f"*Generated by [MOMentum](https://github.com/HaitaanshDixit/MOMentum)*\n")

    print(f"  Exported MD  : {filepath}")
    return filepath


class _MOMPDF(FPDF):
    """Custom FPDF class with MOMentum header and footer."""

    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(30, 30, 30)
        self.cell(0, 10, "MINUTES OF MEETING", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(100, 100, 100)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Generated by MOMentum  |  Page {self.page_no()}", align="C")


def export_pdf(mom: MOMDocument, output_dir: str = "output") -> str:

    _ensure_output_dir(output_dir)
    filename = _safe_filename(mom.title, "pdf")
    filepath = os.path.join(output_dir, filename)

    pdf = _MOMPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_margins(15, 20, 15)

    # ── Metadata table ──
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(240, 240, 240)

    fields = [
        ("Title", mom.title),
        ("Date", mom.date),
        ("Duration", mom.duration),
        ("Language", mom.language),
        ("Audio File", mom.audio_file),
        ("Generated At", mom.generated_at),
    ]

    for label, value in fields:
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(40, 7, label, border=0, fill=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 7, value, border=0, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)

    def section_header(title: str):
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_fill_color(50, 50, 50)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 8, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(30, 30, 30)
        pdf.ln(2)

    def body_text(text: str):
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, text)
        pdf.ln(2)

    def bullet_list(items: list, empty: str = "None identified.", checkbox: bool = False):
        pdf.set_font("Helvetica", "", 10)
        if not items:
            pdf.set_text_color(150, 150, 150)
            pdf.cell(0, 6, f"  {empty}", new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(30, 30, 30)
        else:
            for item in items:
                prefix = "[ ]  " if checkbox else "-  "
                pdf.multi_cell(0, 6, f"  {prefix}{item}")
        pdf.ln(3)

    section_header("DISCUSSION SUMMARY")
    body_text(mom.overview)

    section_header("ACTION ITEMS")
    bullet_list(mom.action_items, checkbox=True)

    section_header("DECISIONS MADE")
    bullet_list(mom.decisions)

    section_header("NEXT STEPS")
    bullet_list(mom.next_steps)

    pdf.output(filepath)
    print(f"  Exported PDF : {filepath}")
    return filepath


# Main export function 

def export(
    mom: MOMDocument,
    format: str = "md",
    output_dir: str = "output"
) -> str:
    """
    Export a MOMDocument to the specified format.

    Args:
        mom        : MOMDocument from formatter.py
        format     : "txt", "md", or "pdf"
        output_dir : Directory to save the file

    Returns:
        str: Path to the exported file

    Raises:
        ValueError: If format is not supported
    """
    format = format.lower().strip()

    exporters = {
        "txt": export_txt,
        "md":  export_md,
        "pdf": export_pdf,
    }

    if format not in exporters:
        raise ValueError(
            f"Unsupported format: '{format}'\n"
            f"Supported formats: {', '.join(exporters.keys())}"
        )

    return exporters[format](mom, output_dir)

if __name__ == "__main__":
    print("exporter.py — not intended to run standalone.")
    print("Use momentum.py to run the full pipeline.")
