"""
Assembles all pipeline outputs into a structured Minutes of Meeting document object ready for export.
"""

from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

from summarizer import MeetingSummary
from transcriber import TranscriptResult
from preprocessor import AudioProfile


@dataclass
class MOMDocument:
    
    title: str
    date: str
    duration: str
    language: str
    audio_file: str
    generated_at: str

    overview: str
    action_items: list[str] = field(default_factory=list)
    decisions: list[str] = field(default_factory=list)
    next_steps: list[str] = field(default_factory=list)

    whisper_model: str = "base"
    word_count_transcript: int = 0
    review_passes: int = 0
    review_score: int = 0

    def __str__(self):
        sep = "=" * 44

        def fmt_list(items, empty="None identified."):
            if not items:
                return f"  {empty}"
            return "\n".join(f"  [ ] {item}" for item in items)

        def fmt_plain(items, empty="None identified."):
            if not items:
                return f"  {empty}"
            return "\n".join(f"  - {item}" for item in items)

        return (
            f"\n{sep}\n"
            f"       MINUTES OF MEETING\n"
            f"{sep}\n"
            f"  Title        : {self.title}\n"
            f"  Date         : {self.date}\n"
            f"  Duration     : {self.duration}\n"
            f"  Language     : {self.language}\n"
            f"  Audio File   : {self.audio_file}\n"
            f"  Generated At : {self.generated_at}\n"
            f"{sep}\n\n"
            f"  DISCUSSION SUMMARY\n"
            f"  {'-'*40}\n"
            f"  {self.overview}\n\n"
            f"  ACTION ITEMS\n"
            f"  {'-'*40}\n"
            f"{fmt_list(self.action_items)}\n\n"
            f"  DECISIONS MADE\n"
            f"  {'-'*40}\n"
            f"{fmt_plain(self.decisions)}\n\n"
            f"  NEXT STEPS\n"
            f"  {'-'*40}\n"
            f"{fmt_plain(self.next_steps)}\n\n"
            f"{sep}\n"
            f"  Generated by MOMentum\n"
            f"  https://github.com/HaitaanshDixit/MOMentum\n"
            f"{sep}"
        )



def format_mom(
    profile: AudioProfile,
    transcript: TranscriptResult,
    summary: MeetingSummary,
    review_passes: int = 0,
    review_score: int = 0,
    title: str | None = None,
) -> MOMDocument:
    
    audio_name = Path(profile.audio_file.file_name).stem
    date_str = datetime.now().strftime("%d %B %Y")
    generated_at = datetime.now().strftime("%d %B %Y, %I:%M %p")

    if not title:
        title = f"Meeting - {date_str}" 

    # Map language code to full name
    language_display = profile.language_name if hasattr(profile, "language_name") \
        else transcript.language.upper()

    mom = MOMDocument(
        title=title,
        date=date_str,
        duration=profile.audio_file.duration_formatted,
        language=language_display,
        audio_file=profile.audio_file.file_name,
        generated_at=generated_at,
        overview=summary.overview,
        action_items=summary.action_items,
        decisions=summary.decisions,
        next_steps=summary.next_steps,
        whisper_model=transcript.model_used,
        word_count_transcript=transcript.word_count,
        review_passes=review_passes,
        review_score=review_score,
    )

    print(f"\n  MOM document assembled: '{mom.title}'")
    print(f"  Action items : {len(mom.action_items)}")
    print(f"  Decisions    : {len(mom.decisions)}")
    print(f"  Next steps   : {len(mom.next_steps)}")

    return mom


def format_mom_from_review(
    profile: AudioProfile,
    transcript: TranscriptResult,
    review_result,
    title: str | None = None,
) -> MOMDocument:
    
    return format_mom(
        profile=profile,
        transcript=transcript,
        summary=review_result.refined_summary,
        review_passes=review_result.passes_taken,
        review_score=review_result.final_score,
        title=title,
    )


if __name__ == "__main__":
    print("formatter.py — not intended to run standalone.")
    print("Use momentum.py to run the full pipeline.")
